### ISSUE TITLE
Owe

### ISSUE THREAD

**Issue by ThisMe124** [ArdyBotzz/Fazd-Md#1]
Bangh Cek Code /lib/color.js bagian situ ada tulisan import 🙂 + Gak ada Package chalk

**Comment by ArdyBotzz** [comment]
Iya bang lupa, chalk sekarang jadi type module

**Comment by ThisMe124** [comment]
> Iya bang lupa, chalk sekarang jadi type module

"chalk": "^4.1.2", pakai ini aja work

**Comment by ThisMe124** [comment]
node-fetch gak iso?
